#  Econometria: conceitos e aplicações | Capítulos 1-3; 5 - Regressão Linear Simples

Professor Alexandre Gori Maia

https://www.youtube.com/watch?v=bmfzjH0Bo0Y

In [2]:
######################################
# Importando as libraries
######################################

import pandas as pd
import sklearn.model_selection as ms
import sklearn.linear_model as lm
import matplotlib.pyplot as plt
import numpy as np



In [10]:
Y = np.array([4,8,10,12])
X = np.array([1,4,6,7])
print(X,Y)

[1 4 6 7] [ 4  8 10 12]


In [15]:
print(np.mean(X), np.mean(Y))

4.5 8.5


In [11]:
#desvios em relaçao a media
x = X-np.mean(X)
y = Y-np.mean(Y)
print(x, y)

[-3.5 -0.5  1.5  2.5] [-4.5 -0.5  1.5  3.5]


In [20]:
# variaveis auxiliades

somaxy = np.sum(x*y)
somax2 = np.sum(x**2)
somay2 = np.sum(y**2)
n = 4

print(somaxy, somax2, somay2)

27.0 21.0 35.0


In [16]:
x*y

array([15.75,  0.25,  2.25,  8.75])

In [17]:
x**2

array([12.25,  0.25,  2.25,  6.25])

In [19]:
y**2

array([20.25,  0.25,  2.25, 12.25])

In [21]:
beta = somaxy/somax2
beta

1.2857142857142858

In [22]:
alfa = np.mean(Y) - beta * np.mean(X)
alfa

2.7142857142857135

Variancias


In [24]:
# Estimativa da variancia da regressao
s2 = (somay2 - beta * somaxy)/(n-2)
s2

0.14285714285714235

In [25]:
# estimativas da viariancia dos estimadores
sa2 = (1/n + np.mean(X)**2/somax2) * s2
sa2

0.17346938775510146

# test t

In [26]:
ta = alfa/np.sqrt(sa2)
ta

6.516946235415345